schema = 3

[mod]
  [mod.'github.com/alecthomas/units']
    version = 'v0.0.0-20211218093645-b94a6e3cc137'
    hash = 'sha256-uriYmwxT69xbmWKO/5OAyeMa2lFBOJDrU2KtQh/+ZjY='

  [mod.'github.com/asaskevich/govalidator']
    version = 'v0.0.0-20210307081110-f21760c49a8d'
    hash = 'sha256-5ZVRCOiNcvpmK3/mhtF1Iy0naPFVVhmXXQmC6eaJExk='

  [mod.'github.com/beorn7/perks']
    version = 'v1.0.1'
    hash = 'sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4='

  [mod.'github.com/cespare/xxhash/v2']
    version = 'v2.3.0'
    hash = 'sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY='

  [mod.'github.com/dgryski/go-rendezvous']
    version = 'v0.0.0-20200823014737-9f7001d12a5f'
    hash = 'sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.7.0'
    hash = 'sha256-MdT2rQyQHspPJcx6n9ozkLbsktIOJutOqDuKpNAtoZY='

  [mod.'github.com/go-gost/core']
    version = 'v0.4.1'
    hash = 'sha256-/xwLxqqQNKDhHa2sA3aGTHvS7m0m4b7nUJaf3B/J/aw='

  [mod.'github.com/go-gost/gosocks4']
    version = 'v0.1.0'
    hash = 'sha256-RiMxnB1pzOyel2kWEdZPZiiLuufQY2zNrLFVLrvjAoE='

  [mod.'github.com/go-gost/gosocks5']
    version = 'v0.5.0'
    hash = 'sha256-HUd9hNUVHWgJoN/HWS+0VKFzAhrQ7NJ1bCrrF0d6FnY='

  [mod.'github.com/go-gost/plugin']
    version = 'v0.3.0'
    hash = 'sha256-nLjIDYRTewgZBbIyTOXmKO4TXWZWntnnrlSm2uag+VI='

  [mod.'github.com/go-gost/relay']
    version = 'v0.6.0'
    hash = 'sha256-gTCJXTaJwzZJYiQqwx5tbPwrwfRv4NSPYhzwSreeXng='

  [mod.'github.com/go-gost/tls-dissector']
    version = 'v0.2.0'
    hash = 'sha256-InyLouT92lZYOtTu5NDaIe44S9TWBf7KRQwWcrYVbC4='

  [mod.'github.com/go-gost/x']
    version = 'v0.0.0-20260602102551-942131dafcf5'
    hash = 'sha256-Y60/DdTV38QHEYEd3g61dKs9Z3SE2ZD1JmYPjk3RwKY='
    replaced = 'github.com/wprhvso/gost-x'

  [mod.'github.com/go-redis/redis/v8']
    version = 'v8.11.5'
    hash = 'sha256-KhVE/KR5oUCOQ42Hk7J7oa99A1Gu4+KJYknhgYI2G6w='

  [mod.'github.com/gobwas/glob']
    version = 'v0.2.3'
    hash = 'sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc='

  [mod.'github.com/google/btree']
    version = 'v1.1.3'
    hash = 'sha256-/6Us2eNRFi2IIp7p5uPUXLridilAdk4SmZhcTYR0csw='

  [mod.'github.com/google/shlex']
    version = 'v0.0.0-20191202100458-e7afc7fbc510'
    hash = 'sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM='

  [mod.'github.com/gorilla/websocket']
    version = 'v1.5.3'
    hash = 'sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0='

  [mod.'github.com/gravitational/trace']
    version = 'v1.1.16-0.20220114165159-14a9a7dd6aaf'
    hash = 'sha256-JHOtgb0QPL7j8wxpa5lebd3U5zlzWcVZxRfj5cNPpqY='

  [mod.'github.com/hashicorp/hcl']
    version = 'v1.0.0'
    hash = 'sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA='

  [mod.'github.com/jonboulle/clockwork']
    version = 'v0.2.2'
    hash = 'sha256-ryvMsRMd1CeuYyyLTfGRWb36AbZyxtomPBEB7hzrrqE='

  [mod.'github.com/magiconair/properties']
    version = 'v1.8.7'
    hash = 'sha256-XQ2bnc2s7/IH3WxEO4GishZurMyKwEclZy1DXg+2xXc='

  [mod.'github.com/miekg/dns']
    version = 'v1.1.61'
    hash = 'sha256-LVd9lUiyjszM6gdAxTkLF4WZcg25WbUSfP6HttoAAJs='

  [mod.'github.com/mitchellh/mapstructure']
    version = 'v1.5.0'
    hash = 'sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE='

  [mod.'github.com/patrickmn/go-cache']
    version = 'v2.1.0+incompatible'
    hash = 'sha256-+i3/Cd9byb1q926jszLjadiUMUeux0VyGKnmP20EAoA='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.2.2'
    hash = 'sha256-ukxk1Cfm6cQW18g/aa19tLcUu5BnF7VmfAvrDHAOl6A='

  [mod.'github.com/pires/go-proxyproto']
    version = 'v0.8.1'
    hash = 'sha256-3CxfXpx9XGwov2Prq1q02l/WLLIy1g0dM58nb02U/yk='

  [mod.'github.com/prometheus/client_golang']
    version = 'v1.19.1'
    hash = 'sha256-MSLsMDi89uQc7Pa2fhqeamyfPJpenGj3r+eB/UotK7w='

  [mod.'github.com/prometheus/client_model']
    version = 'v0.6.0'
    hash = 'sha256-TAD0mm7msYHo99yoNijeYzlDD0i1Vg3uTetpkDUWQo8='

  [mod.'github.com/prometheus/common']
    version = 'v0.48.0'
    hash = 'sha256-gXer/9So7DxDP3cBQp8sIzJXP5whT8sk31FURoij5Do='

  [mod.'github.com/prometheus/procfs']
    version = 'v0.12.0'
    hash = 'sha256-Y4ZZmxIpVCO67zN3pGwSk2TcI88zvmGJkgwq9DRTwFw='

  [mod.'github.com/rogpeppe/go-internal']
    version = 'v1.12.0'
    hash = 'sha256-qvDNCe3l84/LgrA8X4O15e1FeDcazyX91m9LmXGXX6M='

  [mod.'github.com/rs/xid']
    version = 'v1.3.0'
    hash = 'sha256-a1HtvEujd/C4E/IdXpLazqk+R7dm8fyN9SbY6o3aUHA='

  [mod.'github.com/sagikazarmark/locafero']
    version = 'v0.4.0'
    hash = 'sha256-7I1Oatc7GAaHgAqBFO6Tv4IbzFiYeU9bJAfJhXuWaXk='

  [mod.'github.com/sagikazarmark/slog-shim']
    version = 'v0.1.0'
    hash = 'sha256-F92BQXXmn3mCwu3mBaGh+joTRItQDSDhsjU6SofkYdA='

  [mod.'github.com/sirupsen/logrus']
    version = 'v1.9.3'
    hash = 'sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms='

  [mod.'github.com/sourcegraph/conc']
    version = 'v0.3.0'
    hash = 'sha256-mIdMs9MLAOBKf3/0quf1iI3v8uNWydy7ae5MFa+F2Ko='

  [mod.'github.com/spf13/afero']
    version = 'v1.11.0'
    hash = 'sha256-+rV3cDZr13N8E0rJ7iHmwsKYKH+EhV+IXBut+JbBiIE='

  [mod.'github.com/spf13/cast']
    version = 'v1.6.0'
    hash = 'sha256-hxioqRZfXE0AE5099wmn3YG0AZF8Wda2EB4c7zHF6zI='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.5'
    hash = 'sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw='

  [mod.'github.com/spf13/viper']
    version = 'v1.19.0'
    hash = 'sha256-MZ8EAvdgpGbw6kmUz8UOaAAAMdPPGd14TrCBAY+A1T4='

  [mod.'github.com/subosito/gotenv']
    version = 'v1.6.0'
    hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='

  [mod.'github.com/vishvananda/netlink']
    version = 'v1.1.1-0.20211118161826-650dca95af54'
    hash = 'sha256-5PQbPfcgUP3HgLMQtPQxpvD0ebsZE0iiGGlG6z9FSKI='

  [mod.'github.com/vishvananda/netns']
    version = 'v0.0.4'
    hash = 'sha256-tEba2cxyk3GdCYvEIttQ8aZCzHcB0ZiUt6fUEARDkWU='

  [mod.'github.com/vulcand/predicate']
    version = 'v1.2.0'
    hash = 'sha256-ROAEXPHuStQ8GHsRTYPcL0e49qOnPwITmLG7ot36BWo='

  [mod.'github.com/xjasonlyu/tun2socks/v2']
    version = 'v2.6.0'
    hash = 'sha256-NMs7iP72MJAbRcBybDbNNuvtCUmgllCtU878Kn7hbjw='

  [mod.'github.com/xtaci/smux']
    version = 'v1.5.31'
    hash = 'sha256-rXDNCLfhEgOnEMKLu1uJBgTtu1cZqGXk8JDg0UZFNCQ='

  [mod.'github.com/yl2chen/cidranger']
    version = 'v1.0.2'
    hash = 'sha256-rPZApwakcZ1D3lmZnFds79+TFr9IlYkovTA7o52N9h0='

  [mod.'go.uber.org/multierr']
    version = 'v1.11.0'
    hash = 'sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0='

  [mod.'golang.org/x/crypto']
    version = 'v0.50.0'
    hash = 'sha256-vC1BJT7+3UBWLyEE5n3to0NKhMo6m2HGow2HiFgpQLo='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20241210194714-1829a127f884'
    hash = 'sha256-++9t3dEpkchm4uO6W86oBgqgqberPqOC5anaEybRg9c='

  [mod.'golang.org/x/mod']
    version = 'v0.34.0'
    hash = 'sha256-BJgLn+wh9s/XyS2LDmnXTj4ooR+r0Ew2SlxvJA+6GCs='

  [mod.'golang.org/x/net']
    version = 'v0.53.0'
    hash = 'sha256-G9gKLmyaf6lIV429NKX+YlL6oUPJwlv+BrG6qGhzvmU='

  [mod.'golang.org/x/sync']
    version = 'v0.20.0'
    hash = 'sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y='

  [mod.'golang.org/x/sys']
    version = 'v0.43.0'
    hash = 'sha256-aDQXqSTZES2l/132PBxhZN4ywldpPyfm7LByYCHzzwM='

  [mod.'golang.org/x/term']
    version = 'v0.42.0'
    hash = 'sha256-FCiDvAfq7dgBGQuiDYDFJbj/JPawhrmPF2qdUEftQ1c='

  [mod.'golang.org/x/text']
    version = 'v0.36.0'
    hash = 'sha256-/0t9C6Mc8kYjxweFB0us2lGKo8GovHhBiq5nlMOppC0='

  [mod.'golang.org/x/time']
    version = 'v0.12.0'
    hash = 'sha256-Cp3oxrCMH2wyxjzr5SHVmyhgaoUuSl56Uy00Q7DYEpw='

  [mod.'golang.org/x/tools']
    version = 'v0.43.0'
    hash = 'sha256-CqwqQl9inMT0/5LJ8hmV3HNR1XdI/xBFbi3305VJUlo='

  [mod.'golang.zx2c4.com/wintun']
    version = 'v0.0.0-20230126152724-0fa3db229ce2'
    hash = 'sha256-cjMLNjKnnupVROWmeASORVieAL9ieYdzX3cFzG8bCpo='

  [mod.'golang.zx2c4.com/wireguard']
    version = 'v0.0.0-20250521234502-f333402bd9cb'
    hash = 'sha256-ro/hkx8UYMYDBrnAqNtyVTxDgnrqnSl0b45PfPBclro='

  [mod.'google.golang.org/genproto/googleapis/rpc']
    version = 'v0.0.0-20251202230838-ff82c1b0f217'
    hash = 'sha256-I3ZNpNjKKvTq4DVNw3wLKrCuORabZ0oYj0KKhOMI/MA='

  [mod.'google.golang.org/grpc']
    version = 'v1.79.3'
    hash = 'sha256-mO9ZI8ONBMEBTlrwIPeQMfb3C9ru5zPb26P+uG/pIzY='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.10'
    hash = 'sha256-gUrj1qSpjcpRKCBnrYlKMm+P0OSh7B/8EBREstwhD1w='

  [mod.'gopkg.in/ini.v1']
    version = 'v1.67.0'
    hash = 'sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4='

  [mod.'gopkg.in/natefinch/lumberjack.v2']
    version = 'v2.2.1'
    hash = 'sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='

  [mod.'gvisor.dev/gvisor']
    version = 'v0.0.0-20250523182742-eede7a881b20'
    hash = 'sha256-ONpflureM3b74oEDFEH1b/5sbL8BYD3EmZgI+syXs0I='
